// Objetos constantes para fácil acceso (opcional pero recomendado)
export const WORLD_EVENTS: WorldEvents = {
    ENTITY_CREATED: 'WORLD:ENTITY_CREATED',
    ENTITY_DESTROYED: 'WORLD:ENTITY_DESTROYED',
    WORLD_CLEARED: 'WORLD:WORLD_CLEARED',
} as const;

export const SCENE_EVENTS: SceneEvents = {
    LOAD: 'SCENE:LOAD',
    UNLOAD: 'SCENE:UNLOAD',
    CHANGE: 'SCENE:CHANGE',
    READY: 'SCENE:READY',
    INITIALIZE: 'SCENE:INITIALIZE',
    ACTIVATE: 'SCENE:ACTIVATE',
    DEACTIVATE: 'SCENE:DEACTIVATE',
    ENTER: 'SCENE:ENTER',
    UPDATE: 'SCENE:UPDATE',
    EXIT: 'SCENE:EXIT',
    DESTROY: 'SCENE:DESTROY',
    CLEARED: 'SCENE:CLEARED',
    ENTITY_ADDED: 'SCENE:ENTITY_ADDED',
    ENTITY_REMOVED: 'SCENE:ENTITY_REMOVED',
} as const;


export const INPUT_EVENTS: InputEvents = {
    ACTION: "INPUT:ACTION",
    MOUSE_PRIMARY_ACTION: "INPUT:MOUSE_PRIMARY_ACTION",
    MOUSE_SECONDARY_ACTION: "INPUT:MOUSE_SECONDARY_ACTION",
    KEYDOWN: "INPUT:KEYDOWN",
    KEYUP: "INPUT:KEYUP",
    MOUSEDOWN: "INPUT:MOUSEDOWN",
    MOUSEUP: "INPUT:MOUSEUP",
    MOUSEMOVE: "INPUT:MOUSEMOVE",
    MOUSEWHEEL: "INPUT:MOUSEWHEEL",
    TOUCHSTART: "INPUT:TOUCHSTART",
    TOUCHEND: "INPUT:TOUCHEND",
    TOUCHMOVE: "INPUT:TOUCHMOVE"
} as const;

export const ENGINE_EVENTS: EngineEvents = {
    INITIALIZING: 'ENGINE:INITIALIZING',
    INITIALIZED: 'ENGINE:INITIALIZED',
    INITIALIZATION_ERROR: 'ENGINE:INITIALIZATION_ERROR',
    STARTED: 'ENGINE:STARTED',
    STOPPED: 'ENGINE:STOPPED',
    PAUSED: 'ENGINE:PAUSED',
    RESUMED: 'ENGINE:RESUMED',
    DESTROYED: 'ENGINE:DESTROYED',
    SYSTEM_ADDED: 'ENGINE:SYSTEM_ADDED',
    SYSTEM_REMOVED: 'ENGINE:SYSTEM_REMOVED',
    SCENE_ADDED: 'ENGINE:SCENE_ADDED',
    SCENE_REMOVED: 'ENGINE:SCENE_REMOVED',
    ACTIVE_SCENE_CHANGE: 'ENGINE:ACTIVE_SCENE_CHANGE',
    CANVAS_RESIZED: 'ENGINE:CANVAS_RESIZED',
    WINDOW_RESIZED: 'ENGINE:WINDOW_RESIZED',
    WINDOW_HIDDEN: 'ENGINE:WINDOW_HIDDEN',
    WINDOW_VISIBLE: 'ENGINE:WINDOW_VISIBLE',
    START: 'ENGINE:START',
    STOP: 'ENGINE:STOP',
    PAUSE: 'ENGINE:PAUSE',
    RESUME: 'ENGINE:RESUME',
    ERROR: 'ENGINE:ERROR'
} as const;

export const GAMELOOP_EVENTS: GameLoopEvents = {
    RENDER: 'GAMELOOP:RENDER',
    START: 'GAMELOOP:START',
    STOP: 'GAMELOOP:STOP',
    PAUSE: 'GAMELOOP:PAUSE',
    RESUME: 'GAMELOOP:RESUME',
    STEP: 'GAMELOOP:STEP',
    DESTROY: 'GAMELOOP:DESTROY',
    FPS_UPDATE: 'GAMELOOP:FPS_UPDATE',
    FIXED_UPDATE: 'GAMELOOP:FIXED_UPDATE',
    FIXED_UPDATE_COMPLETE: 'GAMELOOP:FIXED_UPDATE_COMPLETE',
    LATE_UPDATE: 'GAMELOOP:LATE_UPDATE',
    VARIABLE_UPDATE: 'GAMELOOP:VARIABLE_UPDATE',
    VARIABLE_UPDATE_COMPLETE: 'GAMELOOP:VARIABLE_UPDATE_COMPLETE',
    SYSTEM_ERROR: 'GAMELOOP:SYSTEM_ERROR',
} as const;

export const PHYSICS_EVENTS: PhysicsEvents = {
    COLLISION_BEGIN: 'PHYSICS:COLLISION_BEGIN',
    COLLISION_END: 'PHYSICS:COLLISION_END',
    COLLISION_POST_SOLVE: 'PHYSICS:COLLISION_POST_SOLVE',
} as const;

export const ASSET_EVENTS: AssetEvents = {
    LOAD: 'ASSET:LOAD',
    UNLOAD: 'ASSET:UNLOAD',
    LOADED: 'ASSET:LOADED',
    UNLOADED: 'ASSET:UNLOADED',
    ERROR: 'ASSET:ERROR',
    PROGRESS: 'ASSET:PROGRESS',
    CACHE_HIT: 'ASSET:CACHE_HIT',
} as const;
